package com.hengye.share.model.greenrobot;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hengye.share.model.greenrobot.TopicDraft;
import com.hengye.share.model.greenrobot.User;

import com.hengye.share.model.greenrobot.TopicDraftDao;
import com.hengye.share.model.greenrobot.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topicDraftDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TopicDraftDao topicDraftDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topicDraftDaoConfig = daoConfigMap.get(TopicDraftDao.class).clone();
        topicDraftDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        topicDraftDao = new TopicDraftDao(topicDraftDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(TopicDraft.class, topicDraftDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        topicDraftDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public TopicDraftDao getTopicDraftDao() {
        return topicDraftDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
